blogsite/core/views.py
from flask import render_template, request, Blueprint
from blogsite.models import BlogPost

core = Blueprint('core', __name__)

@core.route('/')
def index():
	page = request.args.get('page', 1, type=int)
	blogposts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)

	return render_template('index.html', blogposts=blogposts)

@core.route('/info')
def info():
	return render_template('info.html')

blogsite/posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from blogsite import db
from blogsite.models import BlogPost
from blogsite.posts.forms import BlogPostForm
from blogsite.posts.picture_handler import add_pic

blogposts = Blueprint('blogposts', __name__)

@blogposts.route('/create', methods=['GET', 'POST'])
@login_required
def create():
	form = BlogPostForm()

	if form.validate_on_submit():
		filename = 'default.png'
		if form.picture.data:
			filename = add_pic(form.picture.data)

		blogpost = BlogPost(title=form.title.data,
							picture=filename,
							text=form.text.data,
							user_id=current_user.id)
		db.session.add(blogpost)
		db.session.commit()
		return redirect(url_for('core.index'))
	return render_template('create_post.html', form=form)

@blogposts.route('/<int:blogpost_id>')
def blogpost(blogpost_id):
	blogpost = BlogPost.query.get_or_404(blogpost_id)
	return render_template('blogpost.html', title=blogpost.title, date=blogpost.date,post=blogpost)

@blogposts.route('/<int:blogpost_id>/update', methods=['GET', 'POST'])
def update(blogpost_id):
	blogpost = BlogPost.query.get_or_404(blogpost_id)
	if blogpost.author != current_user:
		abort(403)

	form = BlogPostForm()
	if form.validate_on_submit():
		filename = 'default.png'
		if form.picture.data:
			filename = add_pic(form.picture.data)

		blogpost.title = form.title.data
		blogpost.picture = filename
		blogpost.text = form.text.data
		db.session.add(blogpost)
		db.session.commit()
		return redirect(url_for('blogposts.blogpost', blogpost_id=blogpost.id))

	elif request.method == 'GET':
		form.title.data = blogpost.title
		form.text.data = blogpost.text

	return render_template('create_post.html', title='Update post', form=form)

@blogposts.route('/<int:blogpost_id>/delete', methods=['GET', 'POST'])
def delete(blogpost_id):
	blogpost = BlogPost.query.get_or_404(blogpost_id)
	if blogpost.author != current_user:
		abort(403)

	db.session.delete(blogpost)
	db.session.commit()
	return redirect(url_for('core.index'))

blogsite/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blogsite import db
from blogsite.models import User, BlogPost
from blogsite.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from blogsite.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
	form = RegistrationForm()

	if form.validate_on_submit():
		user = User(email=form.email.data,
					username=form.username.data,
					password=form.password.data)

		db.session.add(user)
		db.session.commit()
		flash('You are now registration!')
		return redirect(url_for('users.login'))
	return render_template('register.html', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user.check_password(form.password.data) and user is not None:
			login_user(user)
			flash('Login success!')

			next = request.args.get('next')

			if next == None or not next[0] == '/':
				next = url_for('core.index')

			return redirect(next)

	return render_template('login.html', form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("core.index"))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateUserForm()
	if form.validate_on_submit():
		if form.picture.data:
			username = current_user.username
			pic = add_profile_pic(form.picture.data, username)
			current_user.profile_image = pic

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('User account updated')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)

	return render_template('account.html', profile_image=profile_image, form=form)

@users.route('/<username>')
def user_posts(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	blogposts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
	return render_template('user_blogposts.html', blogposts=blogposts, user=user)

blogsite/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Account</h1>
    <p class="lead">Welcome, {{ current_user.username }}!</p>
    <img align='center' src="{{url_for('static', filename='profile_pics/' + current_user.profile_image)}}">


	<form method="POST" action="" enctype="multipart/form-data">
  		
			{{ form.hidden_tag() }}
    <div class="form-group">
  			{{ form.email.label(class='form-group') }} {{ form.email(class='form-control') }}<br>
		</div>
		<div class="form-group">
  			{{ form.username.label(class='form-group')  }} {{ form.username(class="form-control")  }}<br>
  		</div>
  		<div class="form-group">
  			{{ form.picture.label(class='form-group')  }} {{ form.picture(class='form-control') }}<br>
  		</div>

  			{{ form.submit() }}
</form>
 </div>
{% endblock %}

blogsite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

		<meta charset="utf-8">
		<title></title>
	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <a class="navbar-brand" href="#">the FLASK blog</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		    <div class="navbar-nav">
		      <a class="nav-link" href="{{ url_for('core.index')}}">Home</a>
		      <a class="nav-link" href="{{ url_for('core.info')}}">Info</a>
		      {% if current_user.is_authenticated %}
		      <a class="nav-link" href="{{ url_for('users.account')}}">Account</a>
		      <a class="nav-link" href="{{ url_for('blogposts.create')}}">Create post</a>
		      <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
		      {% else %}
		      <a class="nav-link" href="{{ url_for('users.register')}}">Register</a>
		      <a class="nav-link" href="{{ url_for('users.login')}}">Login</a>
		      {% endif %}
		    </div>
		  </div>
		</nav>


		<div class="container">
		  {% block content %}

		  {% endblock %}
		</div>
	</body>
</html>

blogsite/templates/blogpost.html
{% extends "base.html" %}
{% block content %}

<div class="card" style="max-width: 750px;">
  <img src="{{url_for('static', filename='posts/' + post.picture)}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p>Published: {{post.date.strftime("%Y-%m-%d")}}. Written by <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a></p>
    <p class="card-text">{{post.text}}</p>
  </div>
</div>


	    {% if post.author == current_user %}
			<a href="{{url_for('blogposts.update', blogpost_id=post.id)}}"><button type="button" class="btn btn-warning">Update</button></a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
	    {% endif %}

	  </div>
	</div>


	<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{url_for('blogposts.delete', blogpost_id=post.id)}}" method='POST'>
        <input type="submit" class="btn btn-danger" value="Delete">
    	</form>
      </div>
    </div>
  </div>
</div>
	  
{% endblock %}

blogsite/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    
    <p class="lead">Create new post</p>

  <form method="POST" action="" enctype="multipart/form-data">
  		
			{{ form.hidden_tag() }}
    <div class="form-group">
  			{{ form.title.label(class='form-group') }} {{ form.title(class='form-control') }}<br>
		</div>
    <div class="form-group">
        {{ form.picture.label(class='form-group')  }} {{ form.picture(class="form-control")  }}<br>
      </div>
		<div class="form-group">
  			{{ form.text.label(class='form-group')  }} {{ form.text(class="form-control")  }}<br>
  		</div>
<div class="form-group">
  			{{ form.submit(class='btn btn-dark') }}
        </div>
</form>
 </div>
{% endblock %}

blogsite/templates/index.html
{% extends "base.html" %}
{% block content %}
	<div class="jumbotron">
	  <h1 class="display-4">Hello, world!</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
<br>
	{% for post in blogposts.items %}

<div class="card" style="max-width: 750px;">
  <img src="{{url_for('static', filename='posts/' + post.picture)}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><a href="{{ url_for('blogposts.blogpost', blogpost_id=post.id) }}">{{post.title}}</a></h5>
    <p>Published: {{post.date.strftime("%Y-%m-%d")}}. Written by <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a></p>
    <p class="card-text">{{post.text}}</p>
  </div>
</div>
<br>
	{% endfor %}
	
	</div>

	<nav aria-label="Page navigation example">
  <ul class="pagination">
  	{% for page_num in blogposts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  	{% if blogposts.page == page_num %}
    <li class="page-item disabled"><a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a></li>
    {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}

blogsite/templates/info.html
{% extends "base.html" %}
{% block content %}
	<div class="jumbotron">
	  <h1 class="display-4">Info</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	  <hr class="my-4">
	  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
	</div>
{% endblock %}

blogsite/templates/login.html
{% extends "base.html" %}
{% block content %}
	<form method="POST">
  		<div class="form-group">
  			{{ form.hidden_tag() }}
  			{{ form.email.label }} {{ form.email(class="form-control") }}<br>
		</div>
  		<div class="form-group">
  			{{ form.password.label }} {{ form.password(class="form-control")  }}<br>
  		</div>
  			{{ form.submit() }}
</form>
{% endblock %}

blogsite/templates/register.html
{% extends "base.html" %}
{% block content %}
	<form method="POST">
  		<div class="form-group">
  			{{ form.hidden_tag() }}
  			{{ form.email.label }} {{ form.email(class="form-control") }}<br>
		</div>
		<div class="form-group">
  			{{ form.username.label }} {{ form.username(class="form-control")  }}<br>
  		</div>
  		<div class="form-group">
  			{{ form.password.label }} {{ form.password(class="form-control")  }}<br>
  		</div>
  		<div class="form-group">
  			{{ form.pass_confirm.label }} {{ form.pass_confirm(class="form-control")  }}<br><br>
  		</div>
  			{{ form.submit() }}
</form>
{% endblock %}

blogsite/templates/user_blogposts.html
{% extends "base.html" %}
{% block content %}
	
	  {% for post in blogposts.items %}

	  <div class="card" style="max-width: 750px;">
  <img src="{{url_for('static', filename='posts/' + post.picture)}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p>Published: {{post.date.strftime("%Y-%m-%d")}}. Written by <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a></p>
    <p class="card-text">{{post.text}}</p>
  </div>
</div>


	  {% endfor %}

	  <nav aria-label="Page navigation example">
  <ul class="pagination">
  	{% for page_num in blogposts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  	{% if blogposts.page == page_num %}
    <li class="page-item disabled"><a class="page-link" href="{{url_for('users.user_posts', username=username, page=page_num)}}">{{page_num}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{url_for('users.user_posts', username=username, page=page_num)}}">{{page_num}}</a></li>
    {% endif %}
    {% endfor %}
  </ul>
</nav>

{% endblock %}